using System.Collections.Generic;
using System.IO;
using System.Reflection;
using BepInEx;
using BepInEx.Configuration;
using HarmonyLib;

namespace pikmanfan2002
{
    class PikminScrapConfig
    {
        public const string CONFIG_FILE_NAME = "PikminScrap.cfg";

        public static ConfigFile config;
        public static ConfigEntry<bool> realisticDoomsdayApparatus;
        public static ConfigEntry<bool> scrapShareSpawn;
        public static ConfigEntry<int> spawnWeightAll;

        // Essentials
        public static ConfigEntry<int> spawnGirdle;
        public static ConfigEntry<int> spawnAquatic;
        public static ConfigEntry<int> spawnFrippery;
        public static ConfigEntry<int> spawnJaw;
        public static ConfigEntry<int> spawnKnuckles;
        public static ConfigEntry<int> spawnCitrus;
        public static ConfigEntry<int> spawnComfort;
        public static ConfigEntry<int> spawnReactor;
        public static ConfigEntry<int> spawnCupid;
        public static ConfigEntry<int> spawnGoo;
        public static ConfigEntry<int> spawnDoomsday;
        public static ConfigEntry<int> spawnDrought;
        public static ConfigEntry<int> spawnWhistle;
        public static ConfigEntry<int> spawnEmerald;
        public static ConfigEntry<int> spawnGlee;
        public static ConfigEntry<int> spawnGyroid;
        public static ConfigEntry<int> spawnHarmonic;
        public static ConfigEntry<int> spawnCask;
        public static ConfigEntry<int> spawnCondo;
        public static ConfigEntry<int> spawnInvigorator;
        public static ConfigEntry<int> spawnLouie;
        public static ConfigEntry<int> spawnSweets;
        public static ConfigEntry<int> spawnLove;
        public static ConfigEntry<int> spawnLuck;
        public static ConfigEntry<int> spawnMassive;
        public static ConfigEntry<int> spawnMirth;
        public static ConfigEntry<int> spawnOlimarnite;
        public static ConfigEntry<int> spawnOmniscient;
        public static ConfigEntry<int> spawnHeart;
        public static ConfigEntry<int> spawnPrototype;
        public static ConfigEntry<int> spawnDiamond;
        public static ConfigEntry<int> spawnROB;
        public static ConfigEntry<int> spawnUgly;
        public static ConfigEntry<int> spawnSpherical;
        public static ConfigEntry<int> spawnStellar;
        public static ConfigEntry<int> spawnGlory;
        public static ConfigEntry<int> spawnSud;
        public static ConfigEntry<int> spawnSunseed;
        public static ConfigEntry<int> spawnSuperstick;
        public static ConfigEntry<int> spawnSuperstrong;
        public static ConfigEntry<int> spawnDreamer;
        public static ConfigEntry<int> spawnTear;
        public static ConfigEntry<int> spawnKey;
        public static ConfigEntry<int> spawnCapsule;
        public static ConfigEntry<int> spawnWiggle;

        // Extras
        public static ConfigEntry<int> spawnAbstract;
        public static ConfigEntry<int> spawnBrake;
        public static ConfigEntry<int> spawnBoom;
        public static ConfigEntry<int> spawnCompelling;
        public static ConfigEntry<int> spawnArchive;
        public static ConfigEntry<int> spawnChime;
        public static ConfigEntry<int> spawnSlicer;
        public static ConfigEntry<int> spawnDisguised;
        public static ConfigEntry<int> spawnArchitect;
        public static ConfigEntry<int> spawnMaterial;
        public static ConfigEntry<int> spawnNapsack;
        public static ConfigEntry<int> spawnFlame;
        public static ConfigEntry<int> spawnFurious;
        public static ConfigEntry<int> spawnVictual;
        public static ConfigEntry<int> spawnJustice;
        public static ConfigEntry<int> spawnLip;
        public static ConfigEntry<int> spawnMemorial;
        public static ConfigEntry<int> spawnMerciless;
        public static ConfigEntry<int> spawnJuggernaut;
        public static ConfigEntry<int> spawnTherapist;
        public static ConfigEntry<int> spawnStrife;
        public static ConfigEntry<int> spawnAntenna;
        public static ConfigEntry<int> spawnToadstool;
        public static ConfigEntry<int> spawnVorpal;
        public static ConfigEntry<int> spawnWorthless;

        // The Rest
        public static ConfigEntry<int> spawnBillboard;
        public static ConfigEntry<int> spawnAmplifier;
        public static ConfigEntry<int> spawnBroken;
        public static ConfigEntry<int> spawnBait;
        public static ConfigEntry<int> spawnCoiled;
        public static ConfigEntry<int> spawnCombustion;
        public static ConfigEntry<int> spawnCorpulent;
        public static ConfigEntry<int> spawnCreative;
        public static ConfigEntry<int> spawnDirector;
        public static ConfigEntry<int> spawnCell;
        public static ConfigEntry<int> spawnEndless;
        public static ConfigEntry<int> spawnExhausted;
        public static ConfigEntry<int> spawnFavorite;
        public static ConfigEntry<int> spawnFond;
        public static ConfigEntry<int> spawnGemstar;
        public static ConfigEntry<int> spawnGeographic;
        public static ConfigEntry<int> spawnHappiness;
        public static ConfigEntry<int> spawnPlatter;
        public static ConfigEntry<int> spawnImpenetrable;
        public static ConfigEntry<int> spawnImperative;
        public static ConfigEntry<int> spawnIndomitable;
        public static ConfigEntry<int> spawnJoyless;
        public static ConfigEntry<int> spawnLost;
        public static ConfigEntry<int> spawnNugget;
        public static ConfigEntry<int> spawnInstrument;
        public static ConfigEntry<int> spawnChampions;
        public static ConfigEntry<int> spawnSatchel;
        public static ConfigEntry<int> spawnMemorable;
        public static ConfigEntry<int> spawnMirrored;
        public static ConfigEntry<int> spawnMainbrain;
        public static ConfigEntry<int> spawnNouveau;
        public static ConfigEntry<int> spawnSilo;
        public static ConfigEntry<int> spawnFlywheel;
        public static ConfigEntry<int> spawnPassion;
        public static ConfigEntry<int> spawnParadoxical;
        public static ConfigEntry<int> spawnPatience;
        public static ConfigEntry<int> spawnPondering;
        public static ConfigEntry<int> spawnProton;
        public static ConfigEntry<int> spawnQuenching;
        public static ConfigEntry<int> spawnScrumptious;
        public static ConfigEntry<int> spawnGreed;
        public static ConfigEntry<int> spawnSpace;
        public static ConfigEntry<int> spawnFlogger;
        public static ConfigEntry<int> spawnMattress;
        public static ConfigEntry<int> spawnOintment;
        public static ConfigEntry<int> spawnThirst;
        public static ConfigEntry<int> spawnTreasured;
        public static ConfigEntry<int> spawnCom;
        public static ConfigEntry<int> spawnVacuum;
        public static ConfigEntry<int> spawnGoodness;
        public static ConfigEntry<int> spawnTyrant;

        public void Init()
        {
            var filePath = Path.Combine(Paths.ConfigPath, CONFIG_FILE_NAME);
            config = new ConfigFile(filePath, true);
            config.SaveOnConfigSet = false;

            realisticDoomsdayApparatus = config.Bind("General", "Realistic Doomsday Apparatus", false, "Makes the Doomsday Apparatus more Doomsday Apparatus-y.");
            scrapShareSpawn = config.Bind("General", "Universal Scrap Spawn", false, "Lets you override all 121 scrap's spawn odds at once.");
            spawnWeightAll = config.Bind("General", "Universal Spawn Odds", 2, "Universal spawn weight for every scrap (121 in total).");

            spawnAbstract = config.Bind("Scrap Weight", "Abstract Masterpiece", 2);
            spawnGirdle = config.Bind("Scrap Weight", "Adamantine Girdle", 2);
            spawnBrake = config.Bind("Scrap Weight", "Air Brake", 2);
            spawnBillboard = config.Bind("Scrap Weight", "Alien Billboard", 2);
            spawnAmplifier = config.Bind("Scrap Weight", "Amplified Amplifier", 2);
            spawnAquatic = config.Bind("Scrap Weight", "Aquatic Mine", 2);
            spawnFrippery = config.Bind("Scrap Weight", "Arboreal Frippery", 2);
            spawnJaw = config.Bind("Scrap Weight", "Behemoth Jaw", 2);
            spawnBoom = config.Bind("Scrap Weight", "Boom Cone", 2);
            spawnBroken = config.Bind("Scrap Weight", "Broken Food Master", 2);
            spawnKnuckles = config.Bind("Scrap Weight", "Brute Knuckles", 2);
            spawnBait = config.Bind("Scrap Weight", "Bug Bait", 2);
            spawnCitrus = config.Bind("Scrap Weight", "Citrus Lump", 2);
            spawnCoiled = config.Bind("Scrap Weight", "Coiled Launcher", 2);
            spawnCombustion = config.Bind("Scrap Weight", "Combustion Berry", 2);
            spawnComfort = config.Bind("Scrap Weight", "Comfort Cookie", 2);
            spawnCompelling = config.Bind("Scrap Weight", "Compelling Cookie", 2);
            spawnCorpulent = config.Bind("Scrap Weight", "Corpulent Nut", 2);
            spawnArchive = config.Bind("Scrap Weight", "Cosmic Archive", 2);
            spawnReactor = config.Bind("Scrap Weight", "Courage Reactor", 2);
            spawnCreative = config.Bind("Scrap Weight", "Creative Inspiration", 2);
            spawnCupid = config.Bind("Scrap Weight", "Cupid's Grenade", 2);
            spawnChime = config.Bind("Scrap Weight", "Danger Chime", 2);
            spawnGoo = config.Bind("Scrap Weight", "Decorative Goo", 2);
            spawnSlicer = config.Bind("Scrap Weight", "Dimensional Slicer", 2);
            spawnDirector = config.Bind("Scrap Weight", "Director of Destiny", 2);
            spawnDisguised = config.Bind("Scrap Weight", "Disguised Delicacy", 2);
            spawnDoomsday = config.Bind("Scrap Weight", "Doomsday Apparatus", 2);
            spawnArchitect = config.Bind("Scrap Weight", "Dream Architect", 2);
            spawnMaterial = config.Bind("Scrap Weight", "Dream Material", 2);
            spawnDrought = config.Bind("Scrap Weight", "Drought Ender", 2);
            spawnCell = config.Bind("Scrap Weight", "Durable Energy Cell", 2);
            spawnWhistle = config.Bind("Scrap Weight", "Emperor Whistle", 2);
            spawnEndless = config.Bind("Scrap Weight", "Endless Repository", 2);
            spawnEmerald = config.Bind("Scrap Weight", "Eternal Emerald Eye", 2);
            spawnExhausted = config.Bind("Scrap Weight", "Exhausted Superstick", 2);
            spawnFavorite = config.Bind("Scrap Weight", "Favorite Gyro Block", 2);
            spawnNapsack = config.Bind("Scrap Weight", "Five-Man Napsack", 2);
            spawnFlame = config.Bind("Scrap Weight", "Flame of Tomorrow", 2);
            spawnFond = config.Bind("Scrap Weight", "Fond Gyro Block", 2);
            spawnFurious = config.Bind("Scrap Weight", "Furious Adhesive", 2);
            spawnGemstar = config.Bind("Scrap Weight", "Gemstar Husband", 2);
            spawnGeographic = config.Bind("Scrap Weight", "Geographic Projection", 2);
            spawnGlee = config.Bind("Scrap Weight", "Glee Spinner", 2);
            spawnGyroid = config.Bind("Scrap Weight", "Gyroid Bust", 2);
            spawnHappiness = config.Bind("Scrap Weight", "Happiness Embles", 2);
            spawnHarmonic = config.Bind("Scrap Weight", "Harmonic Synthesizer", 2);
            spawnCask = config.Bind("Scrap Weight", "Healing Cask", 2);
            spawnVictual = config.Bind("Scrap Weight", "Hideous Victual", 2);
            spawnPlatter = config.Bind("Scrap Weight", "Hypnotic Platter", 2);
            spawnImpenetrable = config.Bind("Scrap Weight", "Impenetrable Cookie", 2);
            spawnImperative = config.Bind("Scrap Weight", "Imperative Cookie", 2);
            spawnIndomitable = config.Bind("Scrap Weight", "Indomitable CPU", 2);
            spawnCondo = config.Bind("Scrap Weight", "Insect Condo", 2);
            spawnInvigorator = config.Bind("Scrap Weight", "Invigorator", 2);
            spawnJoyless = config.Bind("Scrap Weight", "Joyless Jewel", 2);
            spawnJustice = config.Bind("Scrap Weight", "Justice Alloy", 2);
            spawnLouie = config.Bind("Scrap Weight", "King of Bugs", 2);
            spawnSweets = config.Bind("Scrap Weight", "King of Sweets", 2);
            spawnLip = config.Bind("Scrap Weight", "Lip Service", 2);
            spawnLost = config.Bind("Scrap Weight", "Lost Gyro Block", 2);
            spawnNugget = config.Bind("Scrap Weight", "Love Nugget", 2);
            spawnLove = config.Bind("Scrap Weight", "Love Sphere", 2);
            spawnLuck = config.Bind("Scrap Weight", "Luck Wafer", 2);
            spawnMassive = config.Bind("Scrap Weight", "Massive Lid", 2, "the goat");
            spawnInstrument = config.Bind("Scrap Weight", "Master's Instrument", 2);
            spawnChampions = config.Bind("Scrap Weight", "Meat of Champions", 2);
            spawnSatchel = config.Bind("Scrap Weight", "Meat Satchel", 2);
            spawnMemorable = config.Bind("Scrap Weight", "Memorable Gyro Block", 2);
            spawnMemorial = config.Bind("Scrap Weight", "Memorial Shell", 2);
            spawnMerciless = config.Bind("Scrap Weight", "Merciless Extractor", 2);
            spawnMirrored = config.Bind("Scrap Weight", "Mirrored Stage", 2);
            spawnMirth = config.Bind("Scrap Weight", "Mirth Sphere", 2);
            spawnMainbrain = config.Bind("Scrap Weight", "Network Mainbrain", 2);
            spawnNouveau = config.Bind("Scrap Weight", "Nouveau Table", 2);
            spawnSilo = config.Bind("Scrap Weight", "Nutrient Silo", 2);
            spawnOlimarnite = config.Bind("Scrap Weight", "Olimarnite Shell", 2);
            spawnFlywheel = config.Bind("Scrap Weight", "Omega Flywheel", 2);
            spawnOmniscient = config.Bind("Scrap Weight", "Omniscient Sphere", 2);
            spawnPassion = config.Bind("Scrap Weight", "Pale Passion", 2);
            spawnParadoxical = config.Bind("Scrap Weight", "Paradoxical Enigma", 2);
            spawnPatience = config.Bind("Scrap Weight", "Patience Tester", 2);
            spawnHeart = config.Bind("Scrap Weight", "Petrified Heart", 2);
            spawnPondering = config.Bind("Scrap Weight", "Pondering Emblem", 2);
            spawnProton = config.Bind("Scrap Weight", "Proton AA", 2);
            spawnPrototype = config.Bind("Scrap Weight", "Prototype Detector", 2);
            spawnQuenching = config.Bind("Scrap Weight", "Quenching Emblem", 2);
            spawnDiamond = config.Bind("Scrap Weight", "Regal Diamond", 2);
            spawnROB = config.Bind("Scrap Weight", "Remembered Old Buddy", 2);
            spawnJuggernaut = config.Bind("Scrap Weight", "Repair Juggernaut", 2);
            spawnUgly = config.Bind("Scrap Weight", "Rubber Ugly", 2);
            spawnScrumptious = config.Bind("Scrap Weight", "Memorial Shell", 2);
            spawnGreed = config.Bind("Scrap Weight", "Seed of Greed", 2);
            spawnTherapist = config.Bind("Scrap Weight", "Shock Therapist", 2);
            spawnSpace = config.Bind("Scrap Weight", "Space Wave Receiver", 2);
            spawnSpherical = config.Bind("Scrap Weight", "Spherical Atlas", 2);
            spawnFlogger = config.Bind("Scrap Weight", "Spirit Flogger", 2);
            spawnStellar = config.Bind("Scrap Weight", "Stellar Orb", 2);
            spawnGlory = config.Bind("Scrap Weight", "Stone of Glory", 2);
            spawnStrife = config.Bind("Scrap Weight", "Strife Monolith", 2);
            spawnMattress = config.Bind("Scrap Weight", "Succulent Mattress", 2);
            spawnSud = config.Bind("Scrap Weight", "Sud Generator", 2);
            spawnAntenna = config.Bind("Scrap Weight", "Sulking Antenna", 2);
            spawnSunseed = config.Bind("Scrap Weight", "Sunseed Berry", 2);
            spawnSuperstick = config.Bind("Scrap Weight", "Superstick Textile", 2);
            spawnSuperstrong = config.Bind("Scrap Weight", "Superstrong Stabilizer", 2);
            spawnOintment = config.Bind("Scrap Weight", "Survival Ointment", 2);
            spawnDreamer = config.Bind("Scrap Weight", "Sweet Dreamer", 2);
            spawnTear = config.Bind("Scrap Weight", "Tear Stone", 2);
            spawnKey = config.Bind("Scrap Weight", "The Key", 2);
            spawnThirst = config.Bind("Scrap Weight", "Thirst Activator", 2);
            spawnCapsule = config.Bind("Scrap Weight", "Time Capsule", 2);
            spawnToadstool = config.Bind("Scrap Weight", "Toxic Toadstool", 2);
            spawnTreasured = config.Bind("Scrap Weight", "Treasured Gyro Block", 2);
            spawnCom = config.Bind("Scrap Weight", "Universal Com", 2);
            spawnVacuum = config.Bind("Scrap Weight", "Vacuum Processor", 2);
            spawnVorpal = config.Bind("Scrap Weight", "Vorpal Platter", 2);
            spawnGoodness = config.Bind("Scrap Weight", "White Goodness", 2);
            spawnWiggle = config.Bind("Scrap Weight", "Wiggle Noggin", 2);
            spawnWorthless = config.Bind("Scrap Weight", "Worthless Statue", 2);
            spawnTyrant = config.Bind("Scrap Weight", "Yellow Taste Tyrant", 2);


            PropertyInfo orphanedEntriesProp = AccessTools.Property(typeof(ConfigFile), "OrphanedEntries");
            var orphanedEntries = (Dictionary<ConfigDefinition, string>)orphanedEntriesProp.GetValue(config);
            orphanedEntries.Clear();
            config.Save();
            config.SaveOnConfigSet = true;
        }

        public static bool RealisticDoomsdayApparatusEnabled => realisticDoomsdayApparatus.Value;
        public static bool PikminScrapUniversalSpawnRates => scrapShareSpawn.Value;
        public static int PikminScrapUniversalSpawnWeight => spawnWeightAll.Value;

    }
}